version: '3.8'

services:
  apache:
    build: .
    container_name: webshop_apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: webshop_db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: php_webshop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"